spring.application.name=MailAggregator
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=secret
spring.flyway.default-schema=bankaggregator

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.datasource.hikari.data-source-properties.options=-c TimeZone=UTC

monobank.token=uUPFVuZ9wDV-q1KgdahMIHRyez20L4_9SN-f8ls7eGas
monobank.account-id=5njU6znBYZ3Oxg0tQcB2og

google.sheet-id=13Aw_ikOXAkkhPJrDzfko0GMd2rJe2_P3ERxP311aIe0